name: pengajuan_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  go_router: ^16.1.0
  get_it: ^7.6.4
  equatable: ^2.0.7
  dartz: ^0.10.1

  uuid: ^4.1.0
  intl: ^0.19.0
  formz: ^0.6.1

  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.2
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
